"""Megahex tiling and megahex-distance for missile range (Melee p.16).

A *megahex* (MH) is the printed map's larger cell: a centre hex plus its six
neighbours -- a 7-hex flower. Missile fire on p.16 penalises DX by the number of
*megahexes* between firer and target, not by raw hex count, so the engine needs
a deterministic hex -> megahex mapping and a megahex-distance.

Tiling scheme
-------------
The centres of the 7-hex flowers tile the plane on a sqrt(7) sublattice of the
hex lattice. Working in axial coordinates ``(q, r) = (cube_x, cube_z)`` the
sublattice is generated by::

    u = (2, 1)      v = (-1, 3)

Each generator has squared length ``q**2 + q*r + r**2 == 7`` and
``det[u, v] == 2*3 - 1*(-1) == 7``, so every fundamental cell holds exactly
seven hexes -- one full flower. The six nearest lattice neighbours of the origin
flower are ``+-u``, ``+-v`` and ``+-(u - v)``; expressed in the lattice's own
integer coordinates ``(a, b)`` those are the six standard axial hex steps
``(1,0), (0,1), (1,-1)`` and their negatives. Megahex coordinates therefore form
an ordinary hex grid, and megahex distance is the ordinary axial hex distance in
``(a, b)`` space.

A hex at axial ``(q, r)`` solves ``a*u + b*v == (q, r)`` for real ``(a, b)``::

    a = (3*q + r) / 7        b = (-q + 2*r) / 7

Rounding lands within one lattice step of the true cell; a 3x3 search around the
rounded pair then selects the flower whose centre is within hex-distance 1 of the
hex (exactly one qualifies, because the flowers partition the plane). The result
is stable and deterministic, depending only on ``(col, row)``.
"""
from __future__ import annotations

from hexarena.hex import Hex, HexLayout

# Generators of the megahex-centre sublattice, in axial (q, r) coordinates.
_U = (2, 1)
_V = (-1, 3)


def _axial(layout: HexLayout, hex_position: Hex) -> tuple[int, int]:
    """Axial ``(q, r)`` of a hex (``q == cube_x``, ``r == cube_z``)."""
    cube_x, _cube_y, cube_z = layout.to_cube(hex_position)
    return cube_x, cube_z


def _center_axial(coord_a: int, coord_b: int) -> tuple[int, int]:
    """Axial ``(q, r)`` of the flower centre for lattice coordinates ``(a, b)``."""
    return (
        coord_a * _U[0] + coord_b * _V[0],
        coord_a * _U[1] + coord_b * _V[1],
    )


def _axial_distance(start: tuple[int, int], end: tuple[int, int]) -> int:
    """Hex distance between two axial ``(q, r)`` points."""
    diff_q = start[0] - end[0]
    diff_r = start[1] - end[1]
    return (abs(diff_q) + abs(diff_r) + abs(diff_q + diff_r)) // 2


def megahex_coord(layout: HexLayout, hex_position: Hex) -> tuple[int, int]:
    """Lattice coordinates ``(a, b)`` of the megahex containing ``hex_position``.

    This is the megahex's stable identity: every hex maps to exactly one
    ``(a, b)`` pair, and the mapping is a pure function of the hex position.
    """
    axial_q, axial_r = _axial(layout, hex_position)
    guess_a = round((3 * axial_q + axial_r) / 7)
    guess_b = round((-axial_q + 2 * axial_r) / 7)

    best_coord = (guess_a, guess_b)
    best_distance = None
    for delta_a in (-1, 0, 1):
        for delta_b in (-1, 0, 1):
            candidate_a = guess_a + delta_a
            candidate_b = guess_b + delta_b
            center = _center_axial(candidate_a, candidate_b)
            distance = _axial_distance((axial_q, axial_r), center)
            if best_distance is None or distance < best_distance:
                best_distance = distance
                best_coord = (candidate_a, candidate_b)
    return best_coord


def megahex_distance(layout: HexLayout, start: Hex, end: Hex) -> int:
    """Number of megahex steps between the flowers holding ``start`` and ``end``.

    Zero when both hexes share a megahex; one for adjacent megahexes; and so on.
    This is the ``MH`` quantity the p.16 missile-range table is stated in.
    """
    start_coord = megahex_coord(layout, start)
    end_coord = megahex_coord(layout, end)
    return _axial_distance(start_coord, end_coord)
